### PR TITLE
Repair Broken Links in Readme File

### PR DESCRIPTION
**Pull request by LogalDeveloper**
Building on pull request #702, I repaired a few additional links which were broken in the readme file.

### CODE REVIEW

**Comment by kdaniel2410** [comment]
You should edit the README_template.md [here](https://github.com/Javacord/Javacord/blob/master/.github/README_template.md) rather than the README.md directly. That is why all checks have failed.

Otherwise though ty.

**Comment by KILLEliteMaste** [comment]
Can you please rebase to the latest version and squash the PR into a single commit?

**Comment by LogalDeveloper** [comment]
I have completed the requested rebase and squash.

**Comment by KILLEliteMaste** [comment]
Thank you 🙂

**Pull request merged**
