### PR TITLE
Added CompletableFutures for Channels, Guilds, etc

### PR DESCRIPTION
**Pull request by RealYusufIsmail**
## Checklist
- [ ] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](./CONTRIBUTING.md).

## Changelog
In this pr I have added CompletableFutures for Channels, Guilds and more.

### Breaking Changes
Moved the interface member to the API folder instead of core

## Description
If there is any suggestions can you let me know please

Closes: #928 
Closes: #814

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

Additions
- [x] request Server
- [x] request channels
- [ ] request sticker
- [x] request member
- [ ] request role

### CODE REVIEW

**Comment by Saladoc** [comment]
> In this pr I have added CompletableFutures for Channels, Guilds and more.
`CompletableFuture`s are a part of the standard library, they don't need adding. You probably mean "Added request methods for Channels, ..." 

> Moved the interface member to the API folder instead of core
Absolutely not. Exposing `Member` is a major change that is not as simple as moving the interface. See #1095 for the progress on that change and the cascading api changes.

**Comment by KILLEliteMaste** [comment]
I don't think it is a good idea to add these methods at the moment. There is no purpose for requesting a server or channel, because they are essential for Javacord and are always cached. It would be better if we add these methods once we have a REST module like proposed in this issue #356 .
And like Saladoc mentioned, for exposing the member interface a much bigger refactor is required. Btw. the current development is continued on the `refactor/expose-member` Javacord branch because there is still quiet a bit todo so everyone can contribute with PRs

**Comment by RealYusufIsmail** [comment]
Ah i see, will close this pr then

**Comment by wasdennnoch** [comment]
> are always cached

Not with sharding; it's sometimes useful to fetch guilds from different shards, especially since a lot of Javacord methods require full instances of entities and not just IDs. But yeah, given the large pending member refactor, any other big refactors should probably wait, and the sharding thing might be fixed by a more low-level REST module, depending on how that will be architectured.

**Pull request closed without merging**
