### PR TITLE
made some tweaks to the identify payload

### PR DESCRIPTION
**Pull request by RealYusufIsmail**
As seen here https://discord.com/developers/docs/change-log#updated-connection-property-field-names the $ for os, browser and device are no longer required. Also referring_domain, and referrer are no longer needed.

### CODE REVIEW

**Comment by RealYusufIsmail** [comment]
@KILLEliteMaste

**Comment by KILLEliteMaste** [comment]
> @KILLEliteMaste

?

**Comment by RealYusufIsmail** [comment]
can you review this please

**Review by Saladoc — CHANGES_REQUESTED** [review]
Okay first of all, please use meaningful issue titles and commit messages. "tweaks to the identify payload" conveys absolutely zero information about WHAT was "tweaked" and WHY it was. 

Secondly, it appears that the change is for api gateway version 10. Javacord still uses version 9, the issue for the upgrade is #960. You'll either need to verify that this change without the gateway version bump does not break the code or clearly mark this pr to be merged after #960 is resolved.

~~Thirdly, pull requests are to be made against the `development` branch. Please also rebase your changes to remove conflicts rather than littering the commit log with merge commits.~~

Last but not least, please verbalize your requests from others. Pinging someone without any additional information is the equivalent of throwing a peanut at them to get their attention and hoping they glean what you want from mere context. It's unhelpful and depending on the situation and person might even be considered rude.

**Comment by KILLEliteMaste** [comment]
>Thirdly, pull requests are to be made against the development branch. Please also rebase your changes to remove conflicts rather than littering the commit log with merge commits.

This is wrong as we have moved the development to the master branch. See #560

**Comment by RealYusufIsmail** [comment]
I will add this to #994

**Pull request closed without merging**
