### PR TITLE
Fixes for ServerVoiceChannel audio connection

### PR DESCRIPTION
**Pull request by KILLEliteMaste**
## Checklist
- [x] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](./CONTRIBUTING.md).

## Changelog
- Fixed moving the audio connection to the new ServervoiceChannel if the bot gets moved
- Fixed not closing the audio connection when kicking the bot from a ServerVoiceChannel

## Description
This PR fixes some issues with the audio connection. The audio connection will now be closed when kicking the bot from a ServerVoiceChannel and the audio connection will be moved to the new ServerVoiceChannel if the bot gets moved

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

### CODE REVIEW

**Comment by Mysterypotatoguy** [comment]
It's not documented still but the method for moving between audio channels (even moves initiated by other users) was changed when servers changed away from having set audio regions.
Moves now cause the current websocket to disconnect and require reconnecting to the new channel's websocket address, for which you need to receive both a `VOICE_STATE_UPDATE` and `VOICE_SERVER_UPDATE`
I attempted to rework this a while back but I couldn't fit it into the current architecture

The close-on-kick part looks fine to me

**Comment by KILLEliteMaste** [comment]
> It's not documented still but the method for moving between audio channels (even moves initiated by other users) was changed when servers changed away from having set audio regions.
> Moves now cause the current websocket to disconnect and require reconnecting to the new channel's websocket address, for which you need to receive both a `VOICE_STATE_UPDATE` and `VOICE_SERVER_UPDATE`
> I attempted to rework this a while back but I couldn't fit it into the current architecture

But then my current approach might be better than the broken behavior. At least it works until someone (maybe you?) can rework it properly.

**Comment by Mysterypotatoguy** [comment]
I think it will visually move to the correct channel but the actual audio connection will be dead

**Comment by KILLEliteMaste** [comment]
> I think it will visually move to the correct channel but the actual audio connection will be dead

I tested it and it works pretty good until you move the bot very fast between 2 channels in like <0.5 seconds, then it stops playing. But when you move it afterwards again to a voice channel it starts playing again.

**Comment by Mysterypotatoguy** [comment]
...Interesting. I will have to take another look when I'm free

**Comment by KILLEliteMaste** [comment]
@Mysterypotatoguy are you okay with this or should this PR not be merged until you had another look on it?

**Review by Mysterypotatoguy — APPROVED** [review]
I'm okay with this being merged if it fixes a majority of the voice moving problems. Can do another pass for the edge cases later

**Pull request merged**
