### PR TITLE
Follow the all-contributors specification

### PR DESCRIPTION
**Pull request by KILLEliteMaste**

### CODE REVIEW

**Comment by Vampire** [comment]
I personally don't like this to clutter the readme to be honest.
Just writing here to be notified.
Discussion if any should be in the according issue.

**Review by Saladoc — APPROVED** [review]

**Comment by KILLEliteMaste** [comment]
@all-contributors please add @KILLEliteMaste for maintenance, code, error, doc, review, question

**Comment by KILLEliteMaste** [comment]
@all-contributors please add @KILLEliteMaste for maintenance, code, error, doc, review, question

**Comment by KILLEliteMaste** [comment]
@all-contributors please add @Bastian for maintenance, code, error, doc, review, question

**Comment by KILLEliteMaste** [comment]
@all-contributors please add @Vampire for maintenance, code, error, review, question

**Comment by KILLEliteMaste** [comment]
@all-contributors please add @bassner for maintenance, code, error, review, question

**Comment by KILLEliteMaste** [comment]
@all-contributors please add @Mysterypotatoguy for maintenance, code, error, review, question

**Pull request merged**
