### PR TITLE
Throttle web socket frame sending to ensure not hitting the 120/60 ratelimit (#354)

### LINKED ISSUE #354: Prevent hitting the websocket ratelimits
Javacord should automatically throttle websocket packets to prevent hitting the 120/60 ratelimit.
At the moment it's nearly impossible to hit this ratelimit, but it might become a problem once Javacord has audio support.

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #354

### CODE REVIEW

**Comment by Vampire** [comment]
new version pushed

**Comment by Vampire** [comment]
I didn't test it on the audio branch as I don't use the audio branch yet, but I did my best to port over my changes properly.

**Comment by Bastian** [comment]
https://github.com/Vampire/Javacord/blob/web-socket-frame-sending-throttling/javacord-core/src/main/java/org/javacord/core/util/gateway/DiscordWebSocketAdapter.java#L777
The `sendVoiceStateUpdate(...)` method still directly accesses the websocket.

Besides that, the code seems to work. 

Just one small suggestion: It's not optimal for debugging that the actual sending of packets does not get logged (besides trace). This can be a little bit confusing. I think it would be best to also log the frame when actually sending it and not only when it gets queued.

**Comment by Vampire** [comment]
Ah, good catch, I didn't look for new code sending frames.
Fixed that and added two debug log lines, one for waiting, one for actual sending.

**Comment by Bastian** [comment]
Thanks! :)

**Pull request merged**
