### PR TITLE
Allow to attach MessageCreateListeners to Webhooks

### PR DESCRIPTION
**Pull request by Vampire**

### CODE REVIEW

**Comment by Bastian** [comment]
I guess it would also make sense to be able to attach listeners to `MessageAuthors` then?
But this can easily be done in a separate PR.

**Comment by Vampire** [comment]
What would that do? Just forward to the user or webhook and throw if webhook but not message create listener? Usually we don't do such stuff but first have to cast or use as....

**Comment by Bastian** [comment]
I'm only talking about message create listeners.
And no, don't "forward" them to the User or Webhook object, as you can only access the Webhook object if you have the appropriate permissions (+ it would be an asynchronous REST-Request).

**Comment by Vampire** [comment]
Hm, I'm still unsure about the `MessageAuthor`.
The question remains, should it "forward" (logically, not physically) to the `User` and `Webhook`, so that if the listeners for the user are retrieved it is also returned, or should `MessageAuthor` be a first-class citizen and so on.

**Comment by Bastian** [comment]
I think it would be best to forward it logically, but this should be done in another PR.

**Pull request merged**
