### PR TITLE
add intent to example in README

### PR DESCRIPTION
**Pull request by Lainika**
Intent is required for message content

## Checklist
- [X] I have tested this PR[^1].
- [X] I have read the [contributing guidelines](./CONTRIBUTING.md).

## Changelog
*Documentation only*

## Description

Closes: NaN

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

### CODE REVIEW

**Comment by feddevanderlist** [comment]
I would personally vote for either of the 2 following options instead of this:
`.setAllNonPrivilegedIntents()`
or
`setIntents(Intent.MESSAGE_CONTENT)`

Instead of setting all intents and risking security issues or people not thinking about access.

**Comment by Saladoc** [comment]
First option won't work because message content is privileged. Since privileged intents must be enabled in the application dashboard I don't see a harm in setting all intents. There's not really a way to accidently set them all in both steps.

**Comment by KILLEliteMaste** [comment]
First of all thank you for mentioning this issue we currently have in our example :)

I think it is better if you use `addIntent(Intent.MESSAGE_CONTENT)` instead of setting all intents because the user might not need all privileged intents.

> I would personally vote for either of the 2 following options instead of this

Both options will not work. Saladoc already mention the first reason. The 2nd reason is when you use `setIntent` you will override all intents and then you will miss out on the `GUILD_MESSAGES` to receive messages in the first place

**Comment by Lainika** [comment]
Thank you.
Right that's better, thanks for the advice.

**Comment by KILLEliteMaste** [comment]
@all-contributors please add @Lainika for doc

**Pull request merged**
