### PR TITLE
Upgrade Gradle and rework releasing process

### PR DESCRIPTION
**Pull request by Bastian**
# Changes

## Branches

The `development` branch is no longer necessary and development will take place on the `master` branch.

## Publishing

Snapshots are automatically published on every push to the master branch.

To publish a new release, one can simply remove the -SNAPSHOT suffix from the version in the gradle.properties file. This will automatically trigger a GitHub Action that
* Publishes a GitHub Release
* Pushes the new version to Maven Central
* Creates and pushes a new commit that updates the version by one patch level and appends a -SNAPSHOT suffix (e.g., 3.5.0 -> 3.5.1-SNAPSHOT).

## Javadocs

For the Javadocs, we can migrate to javadoc.io: https://www.javadoc.io/doc/org.javacord/javacord-api/latest/index.html
There's no need to host it ourselves. The current `docs.javacord.org` links can redirect to javadoc.io.

## OSGI

OSGI is no longer supported because we have no one familiar with it. Maybe a future PR can re-add OSGI support.

# Migration steps

- Merge this PR
- Disable TeamCity
- Fast-forward merge the development branch into `master`
- Change the base for all PRs to `master`
- Hope that everything works

### CODE REVIEW

**Comment by Bastian** [comment]
@Vampire Are you able to help me with the OSGI support? I have zero experience with OSGI and I'm pretty sure that my current changes completely broke it.

**Comment by KILLEliteMaste** [comment]
@Bastian What is the state of this?

**Comment by Bastian** [comment]
Still work in progress.
The OSGI support is most likely broken, but otherwise it should build the project. I've also migrated some of the existing scripts to the Kotlin DSL.
For the release process, I'm still a little bit unsure how to implement it (most likely ditching the development branch).

**Comment by Bastian** [comment]
If we don't care about OSGI, I think this PR is ready now.

**Pull request merged**
