### PR TITLE
Added DiscordApi#getPrefixedToken

### PR DESCRIPTION
**Pull request by Kaleidox00**

### CODE REVIEW

**Comment by Kaleidox00** [comment]
* "probably WIP" because i dont know where and how the token is accessed later; maybe someone more experienced should take a look at this.

**Comment by Bastian** [comment]
This would break all REST actions for bot accounts.
The proper way to do add this new method without breaking anything
- First rename the old `getToken()` method to `getPrefixToken()` using IntelliJ's refactoring. This will also rename all usages of the method.
- Create a new method `getToken()` which just returns the token without a prefix.
- Adjust the JavaDocs where appropriate

Thanks :)

**Comment by Kaleidox00** [comment]
Fixed all the things I could find; just gotta wait for the checks. 👍

**Comment by Bastian** [comment]
```
I could find
```
Does this mean you updated the methods names manually, or did you refactor them automatically like I suggested it?

**Comment by Vampire** [comment]
Either way, there are no usages of `getToken()`, so he probably got all occurences. :-)

**Comment by Bastian** [comment]
Ok. I just wanted to know if I have to check if he missed any or not.

**Comment by Vampire** [comment]
I know, hence I just checked out the PR branch and made a usage search :-)

**Comment by Vampire** [comment]
Do you really want the merge commit be in the history? :-(
A rebase would look nicer imho.

**Comment by Bastian** [comment]
No, I don't want a mere commit, I just wasn't sure what the `Update branch` button in the GitHub UI does :/

**Pull request merged**
