### PR TITLE
Polish GHA configs

### PR DESCRIPTION
**Pull request by Goooler**
## Checklist
- [x] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](https://github.com/Javacord/Javacord/blob/master/.github/CONTRIBUTING.md).

## Changelog

- Bump GitHub Action versions, some of them were deprecated
- Added the `gradle/gradle-build-action@v2` action to enable caching for Gradle, see https://github.com/gradle/gradle-build-action.

## Description

Closes: NaN

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

### CODE REVIEW

**Review by Saladoc — COMMENTED** [review]
If my understanding of the `gradle/gradle-build-action` is correct, using it without specifying `arguments:` just creates a context in which the results of gradle build step may be cached.

Does this apply no matter how gradle is executed or only if future gradle builds are also done with the `gradle-build-action` action? Is it necessary or sensible to also replace all tasks that do `run: ./gradlew foo bar` with an equivalent gradle-build-action task?

**Comment by Goooler** [comment]
1. Yep.
2. Include the future versions, it's automatically.
3. ./gradlew is enough.

**Review by Saladoc — APPROVED** [review]
In that case, unless @Vampire or @felldo veto it, I don't see any problem to merge it once it's rebased.

**Comment by felldo** [comment]
So far it LGTM!

**Comment by felldo** [comment]
@all-contributos please add @Goooler for code

**Comment by felldo** [comment]
https://github.com/all-contributors please add @Goooler for code

**Comment by felldo** [comment]
@all-contributors please add @Goooler for code

**Pull request merged**
