### PR TITLE
Changed from channel_id to channel for interaction

### PR DESCRIPTION
**Pull request by RealYusufIsmail**
## Checklist
- [x] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](https://github.com/Javacord/Javacord/blob/master/.github/CONTRIBUTING.md).

## Changelog
- Changed from channel_id to channel for interaction

## Description

Closes: #1229 

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

### CODE REVIEW

**Comment by felldo** [comment]
Is there anything preventing you from testing this? Just executing an application command once to see if everything still works

**Comment by RealYusufIsmail** [comment]
> Is there anything preventing you from testing this? Just executing an application command once to see if everything still works

I don't have access to my computer at the moment so don't have a bot token at hand

**Comment by RealYusufIsmail** [comment]
> Is there anything preventing you from testing this? Just executing an application command once to see if everything still works

Might get a chance as i have got access to my authentication codes but depends when i get the chance.

**Comment by RealYusufIsmail** [comment]
Screenshot 2023-04-16 at 11 33 30
works

**Comment by RealYusufIsmail** [comment]
> Is there anything preventing you from testing this? Just executing an application command once to see if everything still works

Screenshot 2023-04-16 at 11 33 30
works

**Pull request merged**
