### PR TITLE
Update server count

### PR DESCRIPTION
**Pull request by coaxial1**
😬

### CODE REVIEW

**Comment by Bastian** [comment]
📈 🎉

You should edit the [README_template.md](https://github.com/Javacord/Javacord/blob/development/.github/README_template.md) file, not the README file directly.

**Comment by Bastian** [comment]
Fixed it for you :)

**Comment by coaxial1** [comment]
Got it, will keep that in mind for the next time :)

**Comment by Bastian** [comment]
Let's hope there will be many next times :-) 🚀

**Pull request merged**
