### PR TITLE
Change name of download methods for consistency

### PR DESCRIPTION
**Pull request by KILLEliteMaste**
Solved #552

### CODE REVIEW

**Comment by Bastian** [comment]
The old methods should get deprecated instead of just being removed.

**Comment by Saladoc** [comment]
It might be prudent to instead of duplicating the implementation code have the old methods be `default` methods on the interfaces and have them call the new method. That way we contain our backwards-compatibility change in the API and it will be easier to remove on the next breaking update.

**Review by Saladoc — APPROVED** [review]
Seeing as we include a huge set of breaking changes in the next release we might just as well forego the deprecation

**Comment by Bastian** [comment]
> Seeing as we include a huge set of breaking changes in the next release we might just as well forego the deprecation

Deprecations are not only to not have breaking changes, but also to make it easier for the user to migrate. When they update, they get a warning and can look at the JavaDocs what the replacement method is. When we just remove the method without deprecation, they just have an error and have to guess the replacement method or read all the changelogs since their last update (not everyone updates regularly).

**Review by Saladoc — CHANGES_REQUESTED** [review]
Following the discussion on Discord we should stick with the earlier plan and keep the older methods, but deprecate them, scheduled to remove in a future release.

**Comment by KILLEliteMaste** [comment]
Added the old methods back and marked them as deprecated

**Review by Saladoc — APPROVED** [review]

**Pull request merged**
