### PR TITLE
Remove and add missing Enum values

### PR DESCRIPTION
**Pull request by felldo**
## Checklist
- [x] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](https://github.com/Javacord/Javacord/blob/master/.github/CONTRIBUTING.md).

## Changelog
- Added missing ServerFeature enum values
- Added missing SystemChannelFlag enum values
- Added missing MessageType enum values
- Added missing PermissionType enum values
- Added missing StickerFormatType enum values
- Added missing UserFlag enum values

### Breaking Changes
- Removed `MONETIZATION_ENABLED` and `PRIVATE_THREADS` ServerFeature enum values as they are no longer in use
- Renamed `PermissionType.MANAGE_EMOJI` to `MANAGE_SERVER_EXPRESSIONS` and `ATTACH_FILE` to `ATTACH_FILES` and `USE_VOICE_ACTIVITY` to `USE_VAD`

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

### CODE REVIEW

**Comment by RealYusufIsmail** [comment]
Shall i close my pr on updating the permission type enums

**Comment by RealYusufIsmail** [comment]
> Shall i close my pr on updating the permission type enums

Will close it as you added the enums I added.

**Review by Saladoc — APPROVED** [review]

**Review by RealYusufIsmail — APPROVED** [review]

**Comment by felldo** [comment]
> > Shall i close my pr on updating the permission type enums
> 
> Will close it as you added the enums I added.

I'm sorry, I didn't have your PR in mind where you also added missing PermissionType values

**Comment by RealYusufIsmail** [comment]
> > > Shall i close my pr on updating the permission type enums
> 
> > 
> 
> > Will close it as you added the enums I added.
> 
> 
> 
> I'm sorry, I didn't have your PR in mind where you also added missing PermissionType values

Not a problem

**Pull request merged**
