### PR TITLE
Added NitroType to User

### PR DESCRIPTION
**Pull request by RealYusufIsmail**
## Checklist
- [ ] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](./CONTRIBUTING.md).

## Changelog
- added nitro type to user object

## Description

Closes: NaN

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

### CODE REVIEW

**Comment by Mysterypotatoguy** [comment]
I'm not sure how you tested this, as the `premium_type` field isn't available on users through the gateway. You would need to use OAuth2 with the `identify` scope to be able to fetch this field

**Comment by RealYusufIsmail** [comment]
> I'm not sure how you tested this, as the `premium_type` field isn't available on users through the gateway. You would need to use OAuth2 with the `identify` scope to be able to fetch this field

How would you do that

**Comment by Mysterypotatoguy** [comment]
You would need to use OAuth2 and authenticate with the user, which is out of scope for Javacord currently

**Comment by RealYusufIsmail** [comment]
> You would need to use OAuth2 and authenticate with the user, which is out of scope for Javacord currently

oh ok

**Pull request closed without merging**
