### PR TITLE
added canYouTimeoutUser && canTimeoutUser && canYouTimeoutUsers

### PR DESCRIPTION
**Pull request by RealYusufIsmail**
## Checklist
- [x] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](https://github.com/Javacord/Javacord/blob/master/.github/CONTRIBUTING.md).

## Changelog
- Added convenience methods to check timeout permissions.

## Description

Closes: #1194

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

### CODE REVIEW

**Review by Saladoc — CHANGES_REQUESTED** [review]
Incorrect return values if user has `ADMINISTRATOR` permission but not `MODERATE_MEMBERS`. Please test and fix.

**Comment by Saladoc** [comment]
:+1: Alright, please squash and rebase.

**Comment by RealYusufIsmail** [comment]
> 👍 Alright, please squash, rebase and fill in the changelog in the PR comment.

I cant squish because there is a merge in between so what shall I do?

**Comment by Saladoc** [comment]
> I cant squish because there is a merge in between so what shall I do?

An interactive rebase `git rebase -i master` should do the trick, there you should be able to throw out the merge commit and squash the rest. I rarely deal with merge commits because I liberally rebase, so I can't give you exact guidance here.

**Comment by RealYusufIsmail** [comment]
> Not really, it's still 6 commits to merge. It should be one only. Also you introduced some more changes that should not be part of this pull request.

I think I have broke it

**Pull request closed without merging**
