### PR TITLE
Added Method KnownCustomEmoji#requestCreator

### PR DESCRIPTION
**Pull request by ghost**
Tested.

This closes Issue https://github.com/Javacord/Javacord/issues/364.

-> Had to make the CompletableFuture contain an Optional of a user, because the [Emoji Documentation](https://discordapp.com/developers/docs/resources/emoji) does not ensure the user Object within the emoji object.

### CODE REVIEW

**Comment by Kaleidox00** [comment]
Changed the method so the method completes exceptionally when there was no creator found on the request.

**Comment by WalkerKnapp** [comment]
I don't agree with this change to be honest. It's not that intuitive of behavior for it to throw an exception when there is no creator. I like how it was originally.

**Comment by Bastian** [comment]
Thank you for the PR.

I would like to first solve #377 before merging.
I also have to agree with @WalkerKnapp: It should be `CompletableFuture<Optional<User>>` not `CompletableFuture<User>` with an exception.

**Comment by burdoto** [comment]
As stated in #347 I cannot continue working on this flawlessly, so I will eventually open a new PR with the changes made.

**Comment by burdoto** [comment]
[Closed from my End; won't fix]

**Pull request closed without merging**
