### PR TITLE
Fixed #651

### LINKED ISSUE #651: Update jackson-databind
Javacord is currently using jackson 2.9.3 while the latest is 2.12 which leads to incompatibilities with other programs libraries that also use that but more updated versions.(e.g. twitch4j)

Would be cool to have that fixed here so that one doesn't need to manually (and somewhat blindly) shade an updated version and hope it works.

### PR DESCRIPTION
**Pull request by rmuhamedgaliev**
Updated jackson to 2.11.3

### CODE REVIEW

**Comment by rmuhamedgaliev** [comment]
this commit for #hactoberfest

**Comment by Joshix-1** [comment]
The checks failed, you have to look the error and fix it. https://ci.javacord.org/viewLog.html?buildId=8919&buildTypeId=Javacord_UpdateCommitStatus

**Comment by rmuhamedgaliev** [comment]
Updated

**Comment by Joshix-1** [comment]
Looks good, just squash your commits.

**Comment by rmuhamedgaliev** [comment]
> Looks good, just squash your commits.

done

**Review by Joshix-1 — APPROVED** [review]

**Comment by KILLEliteMaste** [comment]
Will be fixed by #807 where all dependencies will be updated

**Pull request closed without merging**
