### PR TITLE
Provide options to set and update role icons.

### PR DESCRIPTION
**Pull request by ReBlast**
## Checklist
- [x] I have tested this PR[^1].
- [x] I have read the [contributing guidelines](https://github.com/Javacord/Javacord/blob/master/.github/CONTRIBUTING.md).

## Changelog
- Added methods that allow specifying a Role's icon in `RoleBuilder` as well as updating it using `RoleUpdater`.

## Description

Closes: NaN

[^1]: At least started a running bot instance with your changes and triggered an event so your changed code gets executed.

### CODE REVIEW

**Review by felldo — APPROVED** [review]
LGTM!

**Comment by felldo** [comment]
Did you at least create a role / updated a role with an icon to test your changes?

**Comment by ReBlast** [comment]
> Did you at least create a role / updated a role with an icon to test your changes?

Yes, I did. Both tests for creating and updating were successful.

**Comment by felldo** [comment]
@all-contributors please add @ReBlast to code

**Pull request merged**
